import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { BookOpenText, ExternalLink, Loader2, MessageCircle, Newspaper, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type FormKind = "RULE" | "NEWS";
type PostForm = { id?: number; kind: FormKind; slug: string; title: string; summary: string; body: string; published: boolean; position: string };
const blankPost = (): PostForm => ({ kind: "RULE", slug: "", title: "", summary: "", body: "", published: false, position: "0" });

function AdminCommunityContent() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const posts = trpc.communityAdmin.list.useQuery(undefined, { enabled: isAdmin });
  const status = trpc.communityAdmin.status.useQuery(undefined, { enabled: isAdmin });
  const [inviteUrl, setInviteUrl] = useState("");
  const [form, setForm] = useState<PostForm>(blankPost);
  useEffect(() => { if (status.data?.discordInviteUrl) setInviteUrl(status.data.discordInviteUrl); }, [status.data?.discordInviteUrl]);
  const error = (reason: { message: string }) => toast.error(reason.message || "Não foi possível salvar. Tente novamente.");
  const updateInvite = trpc.communityAdmin.updateInvite.useMutation({ onSuccess: () => { toast.success("Convite da comunidade atualizado."); utils.communityAdmin.status.invalidate(); utils.community.status.invalidate(); }, onError: error });
  const createPost = trpc.communityAdmin.create.useMutation({ onSuccess: () => { toast.success("Conteúdo criado."); setForm(blankPost()); utils.communityAdmin.list.invalidate(); utils.community.posts.invalidate(); }, onError: error });
  const updatePost = trpc.communityAdmin.update.useMutation({ onSuccess: () => { toast.success("Conteúdo atualizado."); setForm(blankPost()); utils.communityAdmin.list.invalidate(); utils.community.posts.invalidate(); }, onError: error });
  const deletePost = trpc.communityAdmin.delete.useMutation({ onSuccess: () => { toast.success("Conteúdo removido."); if (form.id) setForm(blankPost()); utils.communityAdmin.list.invalidate(); utils.community.posts.invalidate(); }, onError: error });
  if (loading) return <div className="grid min-h-80 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div>;
  if (!isAdmin) return <div className="grid min-h-80 place-items-center text-center"><div><ShieldCheck className="mx-auto text-rose-300" size={30} /><h1 className="mt-4 text-xl font-bold text-white">Acesso não autorizado</h1><p className="mt-2 text-sm text-slate-400">Apenas administradores podem editar a comunidade.</p></div></div>;
  function saveInvite(event: FormEvent) { event.preventDefault(); updateInvite.mutate({ inviteUrl: inviteUrl.trim() || null }); }
  function savePost(event: FormEvent) { event.preventDefault(); const payload = { kind: form.kind, slug: form.slug.trim().toLowerCase(), title: form.title.trim(), summary: form.summary.trim() || undefined, body: form.body.trim(), published: form.published, position: Number(form.position) || 0 }; if (form.id) updatePost.mutate({ id: form.id, ...payload }); else createPost.mutate(payload); }
  function editPost(post: NonNullable<typeof posts.data>[number]) { setForm({ id: post.id, kind: post.kind, slug: post.slug, title: post.title, summary: post.summary || "", body: post.body, published: post.published, position: String(post.position) }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  return <div className="mx-auto max-w-7xl space-y-6 text-slate-100"><header className="surface-panel relative overflow-hidden rounded-[1.6rem] p-6 sm:flex sm:items-end sm:justify-between"><div className="pointer-events-none absolute right-0 top-0 h-44 w-44 rounded-full bg-indigo-300/10 blur-3xl" /><div className="relative"><p className="section-kicker">COMUNIDADE</p><h1 className="font-display mt-2 text-3xl font-bold text-white">Regras, novidades e Discord</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Gerencie o convite e publique informações oficiais sem expor credenciais ou tokens.</p></div><div className="relative mt-5 flex gap-2 sm:mt-0"><Link href="/rules"><Button variant="outline" className="border-white/10 text-slate-200"><BookOpenText size={16} /> Regras</Button></Link><Link href="/news"><Button variant="outline" className="border-white/10 text-slate-200"><ExternalLink size={16} /> Novidades</Button></Link></div></header>
    <section className="surface-panel rounded-[1.6rem] p-5 sm:p-7"><div className="mb-5 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border border-indigo-300/20 bg-indigo-300/10 text-indigo-100"><MessageCircle size={18} /></div><div><p className="section-kicker">ACESSO DA COMUNIDADE</p><h2 className="font-display mt-1 text-xl font-bold text-white">Convite do Discord</h2></div></div><form onSubmit={saveInvite} className="flex flex-col gap-3 sm:flex-row"><Input value={inviteUrl} onChange={event => setInviteUrl(event.target.value)} placeholder="https://discord.gg/seu-convite" inputMode="url" className="border-white/10 bg-white/5" /><Button type="submit" disabled={updateInvite.isPending} className="bg-emerald-300 text-slate-950 hover:bg-emerald-200">{updateInvite.isPending ? <Loader2 className="animate-spin" /> : <Save size={16} />} Salvar convite</Button>{inviteUrl ? <Button type="button" variant="outline" onClick={() => { setInviteUrl(""); updateInvite.mutate({ inviteUrl: null }); }} className="border-white/10 text-slate-300">Remover</Button> : null}</form><p className="mt-3 text-xs leading-5 text-slate-500">O bot continuará protegido por uma chave exclusiva quando o acesso ao Discord for recuperado.</p></section>
    <section className="grid gap-6 xl:grid-cols-[.95fr_1.05fr]"><form onSubmit={savePost} className="surface-panel rounded-[1.6rem] p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="section-kicker">CONTEÚDO PUBLICÁVEL</p><h2 className="font-display mt-2 text-2xl font-bold text-white">{form.id ? "Editar publicação" : "Nova publicação"}</h2></div>{form.id ? <Button type="button" variant="outline" onClick={() => setForm(blankPost())} className="border-white/10 text-slate-300">Cancelar</Button> : null}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><select value={form.kind} onChange={event => setForm(current => ({ ...current, kind: event.target.value as FormKind }))} className="h-10 rounded-xl border border-white/10 bg-white/5 px-3 text-sm text-white"><option value="RULE">Regra</option><option value="NEWS">Novidade</option></select><Input required value={form.position} onChange={event => setForm(current => ({ ...current, position: event.target.value }))} inputMode="numeric" placeholder="Prioridade" className="border-white/10 bg-white/5" /><Input required value={form.title} onChange={event => setForm(current => ({ ...current, title: event.target.value }))} placeholder="Título" className="border-white/10 bg-white/5 sm:col-span-2" /><Input required value={form.slug} onChange={event => setForm(current => ({ ...current, slug: event.target.value.toLowerCase() }))} placeholder="endereco-da-publicacao" className="border-white/10 bg-white/5 font-mono sm:col-span-2" /><Input value={form.summary} onChange={event => setForm(current => ({ ...current, summary: event.target.value }))} placeholder="Resumo breve (opcional)" maxLength={280} className="border-white/10 bg-white/5 sm:col-span-2" /><textarea required value={form.body} onChange={event => setForm(current => ({ ...current, body: event.target.value }))} placeholder="Conteúdo que será mostrado publicamente" maxLength={8000} rows={8} className="min-h-40 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white outline-none transition placeholder:text-slate-500 focus:border-emerald-300 sm:col-span-2" /><label className="flex items-center gap-2 text-sm text-slate-300 sm:col-span-2"><input type="checkbox" checked={form.published} onChange={event => setForm(current => ({ ...current, published: event.target.checked }))} /> Publicar para todos</label><Button type="submit" disabled={createPost.isPending || updatePost.isPending} className="bg-emerald-300 text-slate-950 hover:bg-emerald-200 sm:col-span-2">{createPost.isPending || updatePost.isPending ? <Loader2 className="animate-spin" /> : <Plus size={16} />} {form.id ? "Salvar alterações" : "Criar conteúdo"}</Button></div></form>
      <div className="surface-panel rounded-[1.6rem] p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border border-emerald-300/20 bg-emerald-300/10 text-emerald-100"><Newspaper size={18} /></div><div><p className="section-kicker">PUBLICAÇÕES</p><h2 className="font-display mt-1 text-2xl font-bold text-white">Conteúdo cadastrado</h2></div></div><div className="mt-6 space-y-3">{posts.isLoading ? <div className="grid h-40 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div> : posts.data?.length ? posts.data.map(post => <article key={post.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-bold tracking-[.13em] text-emerald-200">{post.kind === "RULE" ? "REGRA" : "NOVIDADE"} · {post.published ? "PUBLICADO" : "RASCUNHO"}</p><h3 className="mt-2 font-bold text-white">{post.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-400">{post.summary || post.body}</p></div><div className="flex shrink-0 gap-2"><Button type="button" variant="outline" size="sm" onClick={() => editPost(post)} className="border-white/10 text-xs text-slate-200">Editar</Button><Button type="button" variant="outline" size="icon" onClick={() => { if (window.confirm(`Excluir “${post.title}”?`)) deletePost.mutate({ id: post.id }); }} className="border-rose-300/20 text-rose-200 hover:bg-rose-300/10"><Trash2 size={15} /></Button></div></div></article>) : <div className="grid h-40 place-items-center rounded-2xl border border-dashed border-white/10 p-5 text-center text-sm text-slate-400">Nenhuma regra ou novidade foi criada ainda.</div>}</div></div></section>
  </div>;
}

export default function AdminCommunity() { return <DashboardLayout><AdminCommunityContent /></DashboardLayout>; }
