import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, CheckCircle2, Clock3, ServerCrash, ShieldCheck } from "lucide-react";
import { useState } from "react";

const statusLabel: Record<string, string> = { UNKNOWN: "Aguardando", ONLINE: "Online", DEGRADED: "Atenção", OFFLINE: "Offline" };
const statusClass: Record<string, string> = { UNKNOWN: "border-slate-500/30 bg-slate-500/10 text-slate-300", ONLINE: "border-emerald-400/30 bg-emerald-400/10 text-emerald-200", DEGRADED: "border-amber-400/30 bg-amber-400/10 text-amber-200", OFFLINE: "border-red-400/30 bg-red-400/10 text-red-200" };

function formatDate(value: Date | string | null | undefined) {
  if (!value) return "Ainda não verificado";
  return new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" });
}

export default function AdminMonitoring() {
  const overview = trpc.admin.monitoring.useQuery(undefined, { refetchInterval: 30_000 });
  const history = trpc.admin.monitoringHistory.useQuery({ limit: 40 }, { refetchInterval: 30_000 });
  const [range, setRange] = useState<7 | 30>(7);
  const availability = trpc.admin.monitoringAvailability.useQuery({ days: range }, { refetchInterval: 60_000 });
  const services = overview.data?.services ?? [];
  const incidents = overview.data?.incidents ?? [];
  const online = services.filter(service => service.currentStatus === "ONLINE").length;
  const attention = services.filter(service => service.currentStatus === "DEGRADED").length;

  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6">
    <header className="admin-page-header"><p className="section-kicker">CENTRAL DE SAÚDE</p><h1>Monitoramento operacional</h1><p>Veja a disponibilidade da loja, API, integração Discord e servidor Paper. O agente da VPS verifica os serviços sem interferir em pagamentos ou entregas.</p></header>
    <section className="grid gap-4 sm:grid-cols-3"><Card className="surface-panel border-white/10"><CardContent className="flex items-center gap-3 p-5"><ShieldCheck className="text-emerald-300" /><div><p className="text-xs uppercase tracking-widest text-slate-500">Online</p><strong className="text-2xl text-white">{online}/{services.length || 4}</strong></div></CardContent></Card><Card className="surface-panel border-white/10"><CardContent className="flex items-center gap-3 p-5"><AlertTriangle className="text-amber-300" /><div><p className="text-xs uppercase tracking-widest text-slate-500">Atenção</p><strong className="text-2xl text-white">{attention}</strong></div></CardContent></Card><Card className="surface-panel border-white/10"><CardContent className="flex items-center gap-3 p-5"><ServerCrash className="text-red-300" /><div><p className="text-xs uppercase tracking-widest text-slate-500">Incidentes abertos</p><strong className="text-2xl text-white">{incidents.length}</strong></div></CardContent></Card></section>
    <section className="grid gap-4 md:grid-cols-2">{services.map(service => <Card key={service.serviceKey} className="surface-panel border-white/10"><CardHeader className="flex-row items-start justify-between gap-4 space-y-0"><div><CardTitle className="text-base text-white">{service.label}</CardTitle><p className="mt-1 text-xs text-slate-500">{service.serviceKey.toUpperCase()}</p></div><Badge className={statusClass[service.currentStatus] ?? statusClass.UNKNOWN}>{statusLabel[service.currentStatus] ?? service.currentStatus}</Badge></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">Última verificação</p><p className="mt-1 text-slate-200">{formatDate(service.lastCheckedAt)}</p></div><div><p className="text-xs text-slate-500">Latência</p><p className="mt-1 text-slate-200">{service.lastLatencyMs == null ? "—" : `${service.lastLatencyMs} ms`}</p></div><div className="col-span-2 flex items-center gap-2 border-t border-white/10 pt-3 text-xs text-slate-400"><Activity size={14} />{service.lastMessage || "Sem mensagem do monitor"}<span className="ml-auto">Falhas: {service.consecutiveFailures}</span></div></CardContent></Card>)}</section>
    <section className="grid gap-5 lg:grid-cols-2"><Card className="surface-panel border-white/10"><CardHeader><CardTitle className="flex items-center gap-2 text-white"><AlertTriangle size={17} className="text-amber-300" />Incidentes abertos</CardTitle></CardHeader><CardContent className="space-y-3">{incidents.length ? incidents.map(incident => <div key={incident.id} className="rounded-xl border border-red-400/20 bg-red-400/[.06] p-3"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-red-100">{incident.label}</strong><span className="text-xs text-slate-500">{formatDate(incident.openedAt)}</span></div><p className="mt-1 text-sm text-slate-300">{incident.lastMessage || "Sem detalhe"}</p></div>) : <div className="py-6 text-center text-sm text-slate-400"><CheckCircle2 className="mx-auto mb-2 text-emerald-300" />Nenhum incidente aberto.</div>}</CardContent></Card><Card className="surface-panel border-white/10"><CardHeader><CardTitle className="flex items-center gap-2 text-white"><Clock3 size={17} className="text-emerald-300" />Últimas verificações</CardTitle></CardHeader><CardContent className="max-h-80 space-y-2 overflow-auto">{history.data?.length ? history.data.map(check => <div key={check.id} className="flex items-center gap-3 border-b border-white/[.06] py-2 text-sm last:border-0"><span className={`h-2 w-2 rounded-full ${check.status === "ONLINE" ? "bg-emerald-300" : check.status === "DEGRADED" ? "bg-amber-300" : "bg-red-300"}`} /><span className="min-w-0 flex-1 truncate text-slate-300">{check.label}</span><span className="text-xs text-slate-500">{check.latencyMs ?? "—"} ms</span><span className="text-xs text-slate-500">{formatDate(check.checkedAt)}</span></div>) : <p className="py-6 text-center text-sm text-slate-400">Aguardando o primeiro ciclo do monitor.</p>}</CardContent></Card>    </section>
    <section className="surface-panel rounded-2xl border border-white/10 p-5 sm:p-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker">DADOS OBSERVADOS</p><h2 className="mt-2 text-xl font-bold text-white">Disponibilidade por período</h2><p className="mt-1 text-sm text-slate-400">Percentuais calculados somente a partir dos checks persistidos. Dias sem verificação não são preenchidos artificialmente.</p></div><div className="flex rounded-xl border border-white/10 bg-black/10 p-1" role="group" aria-label="Período do gráfico"><button type="button" onClick={() => setRange(7)} className={`rounded-lg px-3 py-2 text-xs font-semibold transition-colors ${range === 7 ? "bg-emerald-300 text-slate-950" : "text-slate-400 hover:text-white"}`}>7 dias</button><button type="button" onClick={() => setRange(30)} className={`rounded-lg px-3 py-2 text-xs font-semibold transition-colors ${range === 30 ? "bg-emerald-300 text-slate-950" : "text-slate-400 hover:text-white"}`}>30 dias</button></div></div>
      <div className="mt-6 grid gap-5 md:grid-cols-2">{services.map(service => { const points = availability.data?.points.filter(point => point.serviceKey === service.serviceKey) ?? []; const average = points.length ? points.reduce((sum, point) => sum + point.uptimePercent, 0) / points.length : null; return <article key={`chart-${service.serviceKey}`} className="rounded-xl border border-white/[.08] bg-black/10 p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-slate-200">{service.label}</h3><span className="text-sm font-bold text-emerald-200">{average == null ? "—" : `${average.toFixed(2)}%`}</span></div>{points.length ? <div className="mt-4 flex h-24 items-end gap-1.5" aria-label={`Disponibilidade de ${service.label} nos últimos ${range} dias`}>{points.map(point => <div key={`${service.serviceKey}-${point.date}`} className="group relative flex h-full flex-1 items-end" title={`${point.date}: ${point.uptimePercent}% (${point.online}/${point.total})`}><div className={`w-full rounded-t-md transition-all ${point.uptimePercent >= 99 ? "bg-emerald-300" : point.uptimePercent >= 95 ? "bg-amber-300" : "bg-red-300"}`} style={{ height: `${Math.max(8, point.uptimePercent)}%` }} /><span className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-slate-950 px-2 py-1 text-[10px] text-white shadow-lg group-hover:block">{point.date}: {point.uptimePercent}%</span></div>)}</div> : <div className="mt-4 rounded-lg border border-dashed border-white/10 py-8 text-center text-xs text-slate-500">Ainda não há checks reais neste período.</div>}<div className="mt-3 flex justify-between text-[11px] text-slate-500"><span>{points[0]?.date ?? "Sem início"}</span><span>{points[points.length - 1]?.date ?? "Sem fim"}</span></div></article>; })}</div>
    </section>
  </div></DashboardLayout>;
}
