import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BarChart3, Loader2, PackageCheck, Percent, ReceiptText, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

function AdminInsightsContent() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const [period, setPeriod] = useState<"7d" | "30d" | "90d">("30d");
  const input = useMemo(() => ({ period }), [period]);
  const report = trpc.admin.performanceReport.useQuery(input, { enabled: isAdmin });
  const metrics = trpc.admin.metricsByPeriod.useQuery(input, { enabled: isAdmin });
  if (loading) return <div className="grid min-h-80 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div>;
  if (!isAdmin) return <div className="grid min-h-screen place-items-center bg-[#07111d] p-6 text-center text-white"><div><AlertTriangle className="mx-auto text-rose-300" /><h1 className="mt-4 text-2xl font-bold">Área restrita</h1><Link href="/" className="mt-5 inline-flex text-sm font-bold text-emerald-300">Voltar à loja</Link></div></div>;
  const deliveryTotal = report.data?.deliveryStatus.reduce((total, item) => total + item.total, 0) ?? 0;
  const topRevenue = Math.max(1, ...(report.data?.topProducts.map(item => item.revenueCents) ?? [0]));
  return <div className="mx-auto max-w-7xl space-y-5 text-slate-100"><header className="admin-page-header"><div><p className="section-kicker">RELATÓRIOS ADMINISTRATIVOS</p><h1>Resultados claros, sem dados inventados.</h1><p>Leia vendas confirmadas, desempenho real de produtos, cupons e entregas no período selecionado.</p></div><div className="admin-period-filter" aria-label="Período do relatório">{(["7d", "30d", "90d"] as const).map(value => <button type="button" key={value} onClick={() => setPeriod(value)} className={period === value ? "is-active" : ""}>{value === "7d" ? "7 dias" : value === "30d" ? "30 dias" : "90 dias"}</button>)}</div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[{ label: "Faturamento confirmado", value: money.format((metrics.data?.salesCents ?? 0) / 100), detail: `${metrics.data?.paidOrders ?? 0} pedido(s)`, icon: ReceiptText }, { label: "Ticket médio", value: money.format((metrics.data?.averageOrderCents ?? 0) / 100), detail: "Por pedido confirmado", icon: TrendingUp }, { label: "Entregas no período", value: String(deliveryTotal), detail: "Todos os estados", icon: PackageCheck }].map(item => <article key={item.label} className="admin-metric-card"><div><p>{item.label}</p><strong>{item.value}</strong><small>{item.detail}</small></div><span className="grid h-10 w-10 place-items-center rounded-xl border border-sky-300/15 bg-sky-300/[.07] text-sky-100"><item.icon size={18} /></span></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><p className="section-kicker">PRODUTOS</p><h2>Mais relevantes por faturamento</h2><div className="mt-5 space-y-3">{report.isLoading ? <div className="grid min-h-32 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div> : report.data?.topProducts.length ? report.data.topProducts.map(item => <div key={item.productName}><div className="mb-1 flex items-center justify-between gap-3 text-sm"><strong className="truncate text-white">{item.productName}</strong><span className="shrink-0 text-emerald-100">{money.format(item.revenueCents / 100)}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-gradient-to-r from-emerald-300 to-sky-300" style={{ width: `${Math.max(4, Math.round((item.revenueCents / topRevenue) * 100))}%` }} /></div><p className="mt-1 text-xs text-slate-500">{item.units} unidade(s) nos pedidos confirmados</p></div>) : <p className="text-sm text-slate-400">Ainda não há vendas confirmadas neste período.</p>}</div></article><article className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><p className="section-kicker">ENTREGAS</p><h2>Distribuição por estado</h2><div className="mt-5 space-y-2">{report.data?.deliveryStatus.length ? report.data.deliveryStatus.map(item => <div key={item.status} className="flex items-center justify-between rounded-xl border border-white/[.08] bg-white/[.025] p-3"><span className="text-sm text-slate-200">{item.status}</span><Badge className="border-0 bg-white/[.08] text-slate-100">{item.total}</Badge></div>) : <p className="text-sm text-slate-400">Nenhuma entrega criada no período selecionado.</p>}</div></article></section>
    <section className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">CUPONS</p><h2>Uso e impacto comercial</h2><p>Valores baseados exclusivamente em pedidos confirmados que utilizaram cupom.</p></div><Percent className="text-amber-200" size={20} /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-white/[.08] text-xs text-slate-500"><tr><th className="p-3">Cupom</th><th className="p-3 text-right">Usos</th><th className="p-3 text-right">Descontos</th><th className="p-3 text-right">Receita confirmada</th></tr></thead><tbody>{report.data?.coupons.length ? report.data.coupons.map(coupon => <tr key={coupon.couponId} className="border-b border-white/[.06]"><td className="p-3 font-mono text-amber-100">{coupon.code}</td><td className="p-3 text-right text-slate-200">{coupon.uses}</td><td className="p-3 text-right text-slate-200">{money.format(coupon.discountCents / 100)}</td><td className="p-3 text-right font-semibold text-emerald-100">{money.format(coupon.revenueCents / 100)}</td></tr>) : <tr><td colSpan={4} className="p-5 text-center text-slate-400">Nenhum cupom foi aplicado a pedidos confirmados neste período.</td></tr>}</tbody></table></div></section>
    <section className="admin-growth-strip"><BarChart3 size={18} /><p><strong>Leitura responsável:</strong> relatórios não estimam vendas futuras e não incluem pagamentos pendentes, recusados ou cancelados.</p><Link href="/admin/catalog" className="font-bold text-emerald-200 hover:text-emerald-100">Gerenciar catálogo</Link></section>
  </div>;
}

export default function AdminInsights() { return <DashboardLayout><AdminInsightsContent /></DashboardLayout>; }
