import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ChevronLeft, ClipboardList, Filter, Loader2, PackageCheck, RefreshCw, Search, ServerCog, Ticket, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

function AdminOperationsContent() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const orders = trpc.admin.orders.useQuery(undefined, { enabled: isAdmin });
  const deliveries = trpc.admin.deliveries.useQuery(undefined, { enabled: isAdmin });
  const players = trpc.admin.players.useQuery(undefined, { enabled: isAdmin });
  const logs = trpc.admin.logs.useQuery(undefined, { enabled: isAdmin });
  const servers = trpc.admin.servers.useQuery(undefined, { enabled: isAdmin });
  const coupons = trpc.admin.coupons.useQuery(undefined, { enabled: isAdmin });
  const categories = trpc.admin.categories.useQuery(undefined, { enabled: isAdmin });
  const [orderStatus, setOrderStatus] = useState("ALL");
  const [deliveryStatus, setDeliveryStatus] = useState("ALL");
  const [query, setQuery] = useState("");
  const [selectedOrder, setSelectedOrder] = useState<string | null>(null);
  const [selectedPlayer, setSelectedPlayer] = useState<number | null>(null);
  const orderDetail = trpc.admin.orderDetail.useQuery({ id: selectedOrder ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(selectedOrder) });
  const playerHistory = trpc.admin.playerHistory.useQuery({ playerId: selectedPlayer ?? 0 }, { enabled: Boolean(selectedPlayer) });
  const cancelOrder = trpc.admin.cancelOrder.useMutation({ onSuccess: () => { toast.success("Pedido cancelado."); utils.admin.orders.invalidate(); utils.admin.overview.invalidate(); } });
  const retryDelivery = trpc.admin.retryDelivery.useMutation({ onSuccess: () => { toast.success("Entrega recolocada na fila."); utils.admin.deliveries.invalidate(); utils.admin.overview.invalidate(); } });
  const updateServer = trpc.admin.updateServer.useMutation({ onSuccess: () => { toast.success("Servidor atualizado."); utils.admin.servers.invalidate(); } });
  const updateCoupon = trpc.admin.updateCoupon.useMutation({ onSuccess: () => { toast.success("Cupom atualizado."); utils.admin.coupons.invalidate(); } });
  const updateCategory = trpc.admin.updateCategory.useMutation({ onSuccess: () => { toast.success("Categoria atualizada."); utils.admin.categories.invalidate(); utils.catalog.categories.invalidate(); } });

  const visibleOrders = useMemo(() => orders.data?.filter(order => (orderStatus === "ALL" || order.status === orderStatus) && `${order.orderNumber} ${order.playerName}`.toLowerCase().includes(query.toLowerCase())) ?? [], [orders.data, orderStatus, query]);
  const visibleDeliveries = useMemo(() => deliveries.data?.filter(delivery => deliveryStatus === "ALL" || delivery.status === deliveryStatus) ?? [], [deliveries.data, deliveryStatus]);

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#07111d]"><Loader2 className="animate-spin text-emerald-300" /></div>;
  if (!isAdmin) return <div className="grid min-h-screen place-items-center bg-[#07111d] p-6 text-center text-white"><div><AlertTriangle className="mx-auto text-rose-300" /><h1 className="mt-4 text-2xl font-bold">Área restrita</h1><Link href="/" className="mt-5 inline-flex text-sm font-bold text-emerald-300">Voltar à loja</Link></div></div>;

  return <div className="min-h-full bg-[#07111d] text-slate-100"><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-6"><Link href="/admin" className="inline-flex items-center gap-2 text-xs font-bold text-slate-400 hover:text-emerald-200"><ChevronLeft size={15} /> Painel principal</Link><p className="mt-6 font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">OPERAÇÃO</p><h1 className="mt-2 text-3xl font-black tracking-tight text-white">Central de operações</h1><p className="mt-2 text-sm text-slate-400">Filtre, acompanhe e intervenha nos pedidos e entregas com registro de auditoria.</p></header>
    <section className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">PEDIDOS</p><h2 className="mt-1 text-xl font-bold text-white">Consulta e tratamento</h2></div><div className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={15} /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Pedido ou jogador" className="h-9 w-48 border-white/10 bg-white/5 pl-9 text-sm" /></label><select value={orderStatus} onChange={event => setOrderStatus(event.target.value)} className="h-9 rounded-xl border border-white/10 bg-white/5 px-3 text-sm"><option value="ALL">Todos os estados</option><option value="WAITING_PAYMENT">Aguardando pagamento</option><option value="PAID">Pago</option><option value="PROCESSING">Processando</option><option value="COMPLETED">Concluído</option><option value="CANCELLED">Cancelado</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-white/10 text-xs text-slate-500"><tr><th className="p-3">Pedido</th><th className="p-3">Jogador</th><th className="p-3">Status</th><th className="p-3 text-right">Total</th><th className="p-3">Ação</th></tr></thead><tbody>{visibleOrders.map(order => <tr key={order.id} className="border-b border-white/5"><td className="p-3 font-mono font-bold text-white">{order.orderNumber}</td><td className="p-3 text-slate-300">{order.playerName}</td><td className="p-3"><Badge className="bg-white/10 text-slate-200">{order.status}</Badge></td><td className="p-3 text-right font-mono text-emerald-200">{money.format(order.totalCents / 100)}</td><td className="p-3"><div className="flex gap-2"><Button onClick={() => setSelectedOrder(order.id)} size="sm" variant="outline" className="border-white/10">Detalhes</Button>{["PENDING", "WAITING_PAYMENT"].includes(order.status) ? <Button onClick={() => cancelOrder.mutate({ id: order.id })} size="sm" variant="outline" className="border-rose-300/25 text-rose-200 hover:bg-rose-300/10">Cancelar</Button> : null}</div></td></tr>)}</tbody></table></div></section>
    {selectedOrder ? <section className="rounded-[1.6rem] border border-emerald-300/20 bg-emerald-300/[.04] p-5"><div className="flex justify-between gap-4"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">DETALHE DE PEDIDO</p><h2 className="mt-1 text-lg font-bold text-white">{orderDetail.data?.orderNumber ?? "Carregando…"}</h2></div><Button onClick={() => setSelectedOrder(null)} variant="ghost" className="text-slate-300">Fechar</Button></div>{orderDetail.isLoading ? <Loader2 className="mt-5 animate-spin text-emerald-300" /> : <div className="mt-5 grid gap-3 sm:grid-cols-2">{orderDetail.data?.items.map(item => <div key={item.id} className="rounded-xl border border-white/10 bg-slate-950/35 p-3"><p className="font-semibold text-white">{item.productName}</p><p className="mt-1 text-xs text-slate-400">{item.durationDays ? `${item.durationDays} dias` : "Permanente"} · {money.format(item.unitPriceCents / 100)}</p></div>)}</div>}</section> : null}
    <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-5"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">ENTREGAS</p><h2 className="mt-1 text-xl font-bold text-white">Fila e falhas</h2></div><select value={deliveryStatus} onChange={event => setDeliveryStatus(event.target.value)} className="h-9 rounded-xl border border-white/10 bg-white/5 px-3 text-sm"><option value="ALL">Todos</option><option value="PENDING">Pendentes</option><option value="FAILED">Com falha</option><option value="RETRYING">Tentando</option><option value="COMPLETED">Concluídas</option></select></div><div className="space-y-2">{visibleDeliveries.slice(0, 20).map(delivery => <div key={delivery.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[.025] p-3"><div><p className="font-semibold text-white">{delivery.playerName} <span className="font-normal text-slate-500">· {delivery.serverName}</span></p><p className="mt-1 text-xs text-slate-500">Tentativa {delivery.attemptCount}/{delivery.maxAttempts}{delivery.lastError ? ` · ${delivery.lastError}` : ""}</p></div><div className="flex items-center gap-2"><Badge className={delivery.status === "FAILED" ? "bg-rose-300/10 text-rose-200" : "bg-white/10 text-slate-200"}>{delivery.status}</Badge>{["FAILED", "RETRYING", "PENDING"].includes(delivery.status) ? <Button onClick={() => retryDelivery.mutate({ id: delivery.id })} size="icon" variant="outline" className="border-amber-300/25 text-amber-200" title="Reprocessar entrega"><RefreshCw size={15} /></Button> : null}</div></div>)}</div></div>
      <div className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-5"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">JOGADORES</p><h2 className="mt-1 text-xl font-bold text-white">Histórico por jogador</h2><div className="mt-5 space-y-2">{players.data?.slice(0, 20).map(player => <button key={player.id} onClick={() => setSelectedPlayer(player.id)} className="flex w-full items-center justify-between rounded-xl border border-white/10 bg-white/[.025] p-3 text-left hover:bg-white/[.06]"><span><strong className="block text-sm text-white">{player.username}</strong><small className="font-mono text-xs text-slate-500">{player.uuid}</small></span><UserRound size={17} className="text-emerald-300" /></button>)}</div>{selectedPlayer ? <div className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-300/[.05] p-4"><p className="text-xs font-bold text-emerald-200">PEDIDOS DO JOGADOR</p>{playerHistory.isLoading ? <Loader2 className="mt-3 animate-spin text-emerald-300" size={16} /> : <div className="mt-3 space-y-2">{playerHistory.data?.map(order => <p key={order.id} className="text-sm text-slate-300"><span className="font-mono text-xs text-white">{order.orderNumber}</span> · {order.status} · {money.format(order.totalCents / 100)}</p>) || <p className="text-sm text-slate-400">Nenhum pedido encontrado.</p>}</div>}</div> : null}</div></section>
    <section className="grid gap-6 xl:grid-cols-3"><div className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-5"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">CATÁLOGO</p><h2 className="mt-1 text-xl font-bold text-white">Categorias</h2><div className="mt-5 space-y-2">{categories.data?.map(category => <div key={category.id} className="flex items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/[.025] p-3"><span><strong className="block text-sm text-white">{category.name}</strong><small className="text-xs text-slate-500">/{category.slug}</small></span><Button onClick={() => updateCategory.mutate({ id: category.id, name: category.name, slug: category.slug, description: category.description ?? undefined, position: category.position, active: !category.active })} size="sm" variant="outline" className="border-white/10 text-xs">{category.active ? "Ocultar" : "Ativar"}</Button></div>)}</div></div>
      <div className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-5"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">SERVIDORES</p><h2 className="mt-1 text-xl font-bold text-white">Disponibilidade</h2><div className="mt-5 space-y-2">{servers.data?.map(server => <div key={server.id} className="flex items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/[.025] p-3"><span><strong className="block text-sm text-white">{server.name}</strong><small className="text-xs text-slate-500">{server.kind} · chave ···{server.apiKeyLastFour}</small></span><Button onClick={() => updateServer.mutate({ id: server.id, name: server.name, slug: server.slug, kind: server.kind, active: !server.active })} size="sm" variant="outline" className="border-white/10 text-xs">{server.active ? "Desativar" : "Ativar"}</Button></div>)}</div></div>
      <div className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-5"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">CUPONS</p><h2 className="mt-1 text-xl font-bold text-white">Validade</h2><div className="mt-5 space-y-2">{coupons.data?.map(coupon => <div key={coupon.id} className="flex items-center justify-between gap-2 rounded-xl border border-white/10 bg-white/[.025] p-3"><span><strong className="block font-mono text-sm text-white">{coupon.code}</strong><small className="text-xs text-slate-500">{coupon.type === "PERCENTAGE" ? `${(coupon.percentageBasisPoints ?? 0) / 100}%` : money.format((coupon.fixedDiscountCents ?? 0) / 100)}</small></span><Button onClick={() => updateCoupon.mutate({ id: coupon.id, code: coupon.code, type: coupon.type, percentageBasisPoints: coupon.percentageBasisPoints ?? undefined, fixedDiscountCents: coupon.fixedDiscountCents ?? undefined, startsAt: coupon.startsAt, endsAt: coupon.endsAt, maxUses: coupon.maxUses, maxUsesPerPlayer: coupon.maxUsesPerPlayer, active: !coupon.active })} size="sm" variant="outline" className="border-white/10 text-xs">{coupon.active ? "Pausar" : "Ativar"}</Button></div>)}</div></div></section>
    <section className="rounded-[1.6rem] border border-white/10 bg-slate-950/35 p-5"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-emerald-300">AUDITORIA</p><h2 className="mt-1 text-xl font-bold text-white">Eventos recentes</h2><div className="mt-5 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{logs.data?.slice(0, 30).map(log => <div key={log.id} className="rounded-xl border border-white/10 bg-white/[.025] p-3"><p className="font-mono text-xs text-emerald-200">{log.action}</p><p className="mt-1 text-sm text-slate-300">{log.entityType}{log.entityId ? ` · ${log.entityId}` : ""}</p><p className="mt-2 text-xs text-slate-500">{new Date(log.createdAt).toLocaleString("pt-BR")}</p></div>)}</div></section>
  </div></div>;
}

export default function AdminOperations() { return <DashboardLayout><AdminOperationsContent /></DashboardLayout>; }
