import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowLeft, BadgeCheck, CalendarClock, CreditCard, Loader2, MessageCircleMore, PackageCheck, PackageOpen, ShieldCheck, UserRound } from "lucide-react";
import { Link, useRoute } from "wouter";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

function AdminPlayerProfileContent() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const [, params] = useRoute("/admin/players/:id");
  const playerId = Number(params?.id ?? 0);
  const profile = trpc.admin.playerProfile.useQuery({ playerId }, { enabled: isAdmin && Number.isInteger(playerId) && playerId > 0 });

  if (loading) return <div className="grid min-h-80 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div>;
  if (!isAdmin) return <div className="grid min-h-screen place-items-center bg-[#07111d] p-6 text-center text-white"><div><AlertTriangle className="mx-auto text-rose-300" /><h1 className="mt-4 text-2xl font-bold">Área restrita</h1><Link href="/" className="mt-5 inline-flex text-sm font-bold text-emerald-300">Voltar à loja</Link></div></div>;
  if (!Number.isInteger(playerId) || playerId <= 0) return <div className="rounded-2xl border border-rose-300/20 bg-rose-300/[.05] p-6 text-rose-100">Jogador inválido. <Link href="/admin/operations" className="font-bold underline">Voltar às operações</Link></div>;
  if (profile.isLoading) return <div className="grid min-h-80 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div>;
  if (profile.isError || !profile.data) return <div className="rounded-2xl border border-rose-300/20 bg-rose-300/[.05] p-6 text-rose-100">Não foi possível carregar a ficha do jogador. <button type="button" className="font-bold underline" onClick={() => profile.refetch()}>Tentar novamente</button></div>;

  const { profile: player, summary, orders, deliveries, vipGrants, audit } = profile.data;
  return <div className="mx-auto max-w-7xl space-y-5 text-slate-100">
    <header className="admin-page-header"><div><Link href="/admin/operations" className="inline-flex items-center gap-2 text-xs font-bold text-slate-400 hover:text-emerald-200"><ArrowLeft size={14} /> Operações</Link><p className="section-kicker mt-5">FICHA DO JOGADOR</p><h1>{player.username}</h1><p>Histórico comercial, entregas, benefícios e integração Discord reunidos em um único local.</p></div><span className="grid h-14 w-14 place-items-center rounded-2xl border border-emerald-300/20 bg-emerald-300/[.08] text-emerald-100"><UserRound size={25} /></span></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Pedidos pagos", value: summary.paidOrders, icon: CreditCard }, { label: "Total confirmado", value: money.format(summary.totalPaidCents / 100), icon: BadgeCheck }, { label: "VIPs ativos", value: summary.activeVipGrants, icon: ShieldCheck }, { label: "Entregas em tratamento", value: summary.pendingDeliveries, icon: PackageOpen }].map(item => <article key={item.label} className="admin-metric-card"><div><p>{item.label}</p><strong>{item.value}</strong><small>Dados do perfil</small></div><span className="grid h-10 w-10 place-items-center rounded-xl border border-sky-300/15 bg-sky-300/[.07] text-sky-100"><item.icon size={18} /></span></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><article className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><p className="section-kicker">IDENTIDADE E VÍNCULOS</p><h2>Dados de suporte</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4 border-b border-white/[.07] pb-3"><dt className="text-slate-500">UUID</dt><dd className="font-mono text-right text-slate-200">{player.uuid}</dd></div><div className="flex justify-between gap-4 border-b border-white/[.07] pb-3"><dt className="text-slate-500">Última atividade</dt><dd className="text-right text-slate-200">{player.lastSeenAt ? new Date(player.lastSeenAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "Não registrada"}</dd></div><div className="flex justify-between gap-4 border-b border-white/[.07] pb-3"><dt className="text-slate-500">Discord</dt><dd className="flex items-center gap-2 text-right text-slate-200">{player.discordGlobalName ? <><MessageCircleMore size={15} className="text-indigo-200" />{player.discordGlobalName}</> : "Não vinculado"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Vínculo criado</dt><dd className="text-right text-slate-200">{player.discordLinkedAt ? new Date(player.discordLinkedAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "—"}</dd></div></dl></article><article className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><p className="section-kicker">BENEFÍCIOS</p><h2>VIPs e validade</h2><div className="mt-5 space-y-2">{vipGrants.length ? vipGrants.map(grant => <div key={grant.id} className="rounded-xl border border-white/[.08] bg-white/[.025] p-3"><div className="flex items-start justify-between gap-3"><div><strong className="text-white">{grant.productName}</strong><p className="mt-1 text-xs text-slate-400">Grupo {grant.groupName} · {grant.serverName}</p></div><Badge className={`border-0 ${grant.revokedAt ? "bg-slate-300/10 text-slate-300" : grant.expiresAt && grant.expiresAt < new Date() ? "bg-rose-300/10 text-rose-100" : "bg-emerald-300/10 text-emerald-100"}`}>{grant.revokedAt ? "REVOGADO" : grant.expiresAt && grant.expiresAt < new Date() ? "EXPIRADO" : "ATIVO"}</Badge></div><p className="mt-2 text-xs text-slate-500">{grant.expiresAt ? `Expira em ${new Date(grant.expiresAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}` : "Sem expiração"}</p></div>) : <div className="rounded-xl border border-dashed border-white/10 p-5 text-center text-sm text-slate-400">Nenhum benefício VIP registrado para este jogador.</div>}</div></article></section>
    <section className="grid gap-5 xl:grid-cols-2"><article className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><p className="section-kicker">COMPRAS</p><h2>Pedidos e descontos</h2><div className="mt-5 space-y-2">{orders.map(order => <div key={order.id} className="rounded-xl border border-white/[.08] bg-white/[.025] p-3"><div className="flex items-start justify-between gap-3"><div><strong className="font-mono text-sm text-white">{order.orderNumber}</strong><p className="mt-1 text-xs text-slate-400">{new Date(order.createdAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}{order.couponCode ? ` · cupom ${order.couponCode}` : ""}</p></div><div className="text-right"><strong className="text-emerald-100">{money.format(order.totalCents / 100)}</strong><p className="mt-1 text-[11px] text-slate-500">{order.status}</p></div></div>{order.discountCents ? <p className="mt-2 text-xs text-amber-100">Desconto aplicado: {money.format(order.discountCents / 100)}</p> : null}</div>)}</div></article><article className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><p className="section-kicker">ENTREGAS</p><h2>Fila e histórico</h2><div className="mt-5 space-y-2">{deliveries.map(delivery => <div key={delivery.id} className="rounded-xl border border-white/[.08] bg-white/[.025] p-3"><div className="flex items-start justify-between gap-3"><div><strong className="text-white">{delivery.productName}</strong><p className="mt-1 text-xs text-slate-400">{delivery.serverName} · {delivery.orderNumber} · tentativa {delivery.attemptCount}/{delivery.maxAttempts}</p>{delivery.lastError ? <p className="mt-2 text-xs text-rose-200">{delivery.lastError}</p> : null}</div><div className="text-right"><Badge className="border-0 bg-white/[.08] text-slate-200">{delivery.status}</Badge><Link href={`/admin/deliveries/${delivery.id}`} className="mt-2 block text-xs font-bold text-emerald-200 hover:text-emerald-100">Detalhes</Link></div></div></div>)}</div></article></section>
    <section className="surface-panel rounded-[1.4rem] p-5 sm:p-6"><p className="section-kicker">AUDITORIA VINCULADA</p><h2>Eventos do perfil</h2><div className="mt-5 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{audit.length ? audit.map(event => <div key={event.id} className="rounded-xl border border-white/[.08] bg-white/[.025] p-3"><strong className="font-mono text-xs text-emerald-200">{event.action}</strong><p className="mt-1 text-sm text-slate-300">{event.entityType} · {event.actorType}</p><small className="mt-2 block text-xs text-slate-500">{new Date(event.createdAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}</small></div>) : <p className="text-sm text-slate-400">Não há eventos administrativos diretamente vinculados a este jogador.</p>}</div></section>
  </div>;
}

export default function AdminPlayerProfile() { return <DashboardLayout><AdminPlayerProfileContent /></DashboardLayout>; }
