import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, CheckCircle2, Clock3, ServerCrash, ShieldCheck } from "lucide-react";

const statusLabel: Record<string, string> = { UNKNOWN: "Aguardando", ONLINE: "Online", DEGRADED: "Atenção", OFFLINE: "Offline" };
const statusClass: Record<string, string> = { UNKNOWN: "border-slate-500/30 bg-slate-500/10 text-slate-300", ONLINE: "border-emerald-400/30 bg-emerald-400/10 text-emerald-200", DEGRADED: "border-amber-400/30 bg-amber-400/10 text-amber-200", OFFLINE: "border-red-400/30 bg-red-400/10 text-red-200" };

function formatDate(value: Date | string | null | undefined) {
  if (!value) return "Ainda não verificado";
  return new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" });
}

export default function AdminMonitoring() {
  const overview = trpc.admin.monitoring.useQuery(undefined, { refetchInterval: 30_000 });
  const history = trpc.admin.monitoringHistory.useQuery({ limit: 40 }, { refetchInterval: 30_000 });
  const services = overview.data?.services ?? [];
  const incidents = overview.data?.incidents ?? [];
  const online = services.filter(service => service.currentStatus === "ONLINE").length;
  const attention = services.filter(service => service.currentStatus === "DEGRADED").length;

  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6">
    <header className="admin-page-header"><p className="section-kicker">CENTRAL DE SAÚDE</p><h1>Monitoramento operacional</h1><p>Veja a disponibilidade da loja, API, integração Discord e servidor Paper. O agente da VPS verifica os serviços sem interferir em pagamentos ou entregas.</p></header>
    <section className="grid gap-4 sm:grid-cols-3"><Card className="surface-panel border-white/10"><CardContent className="flex items-center gap-3 p-5"><ShieldCheck className="text-emerald-300" /><div><p className="text-xs uppercase tracking-widest text-slate-500">Online</p><strong className="text-2xl text-white">{online}/{services.length || 4}</strong></div></CardContent></Card><Card className="surface-panel border-white/10"><CardContent className="flex items-center gap-3 p-5"><AlertTriangle className="text-amber-300" /><div><p className="text-xs uppercase tracking-widest text-slate-500">Atenção</p><strong className="text-2xl text-white">{attention}</strong></div></CardContent></Card><Card className="surface-panel border-white/10"><CardContent className="flex items-center gap-3 p-5"><ServerCrash className="text-red-300" /><div><p className="text-xs uppercase tracking-widest text-slate-500">Incidentes abertos</p><strong className="text-2xl text-white">{incidents.length}</strong></div></CardContent></Card></section>
    <section className="grid gap-4 md:grid-cols-2">{services.map(service => <Card key={service.serviceKey} className="surface-panel border-white/10"><CardHeader className="flex-row items-start justify-between gap-4 space-y-0"><div><CardTitle className="text-base text-white">{service.label}</CardTitle><p className="mt-1 text-xs text-slate-500">{service.serviceKey.toUpperCase()}</p></div><Badge className={statusClass[service.currentStatus] ?? statusClass.UNKNOWN}>{statusLabel[service.currentStatus] ?? service.currentStatus}</Badge></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">Última verificação</p><p className="mt-1 text-slate-200">{formatDate(service.lastCheckedAt)}</p></div><div><p className="text-xs text-slate-500">Latência</p><p className="mt-1 text-slate-200">{service.lastLatencyMs == null ? "—" : `${service.lastLatencyMs} ms`}</p></div><div className="col-span-2 flex items-center gap-2 border-t border-white/10 pt-3 text-xs text-slate-400"><Activity size={14} />{service.lastMessage || "Sem mensagem do monitor"}<span className="ml-auto">Falhas: {service.consecutiveFailures}</span></div></CardContent></Card>)}</section>
    <section className="grid gap-5 lg:grid-cols-2"><Card className="surface-panel border-white/10"><CardHeader><CardTitle className="flex items-center gap-2 text-white"><AlertTriangle size={17} className="text-amber-300" />Incidentes abertos</CardTitle></CardHeader><CardContent className="space-y-3">{incidents.length ? incidents.map(incident => <div key={incident.id} className="rounded-xl border border-red-400/20 bg-red-400/[.06] p-3"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-red-100">{incident.label}</strong><span className="text-xs text-slate-500">{formatDate(incident.openedAt)}</span></div><p className="mt-1 text-sm text-slate-300">{incident.lastMessage || "Sem detalhe"}</p></div>) : <div className="py-6 text-center text-sm text-slate-400"><CheckCircle2 className="mx-auto mb-2 text-emerald-300" />Nenhum incidente aberto.</div>}</CardContent></Card><Card className="surface-panel border-white/10"><CardHeader><CardTitle className="flex items-center gap-2 text-white"><Clock3 size={17} className="text-emerald-300" />Últimas verificações</CardTitle></CardHeader><CardContent className="max-h-80 space-y-2 overflow-auto">{history.data?.length ? history.data.map(check => <div key={check.id} className="flex items-center gap-3 border-b border-white/[.06] py-2 text-sm last:border-0"><span className={`h-2 w-2 rounded-full ${check.status === "ONLINE" ? "bg-emerald-300" : check.status === "DEGRADED" ? "bg-amber-300" : "bg-red-300"}`} /><span className="min-w-0 flex-1 truncate text-slate-300">{check.label}</span><span className="text-xs text-slate-500">{check.latencyMs ?? "—"} ms</span><span className="text-xs text-slate-500">{formatDate(check.checkedAt)}</span></div>) : <p className="py-6 text-center text-sm text-slate-400">Aguardando o primeiro ciclo do monitor.</p>}</CardContent></Card></section>
  </div></DashboardLayout>;
}
