import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CalendarClock, CheckCircle2, Loader2, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

function displayDate(value: Date | string | null) {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date.toLocaleString("pt-BR", { dateStyle: "medium", timeStyle: "short" });
}

export default function MaintenanceHistory() {
  const history = trpc.store.maintenanceHistory.useQuery();
  return <main className="min-h-screen bg-[#07111d] px-5 py-10 text-slate-100"><section className="mx-auto max-w-3xl"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-emerald-200 hover:text-emerald-100"><ArrowLeft size={16} /> Voltar para a loja</Link><header className="rounded-[1.6rem] border border-emerald-300/15 bg-[radial-gradient(circle_at_top_right,rgba(110,231,183,.12),transparent_42%),rgba(9,24,37,.84)] p-6 sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl border border-emerald-300/25 bg-emerald-300/[.08] text-emerald-200"><ShieldCheck size={23} /></div><p className="section-kicker mt-5">TRANSPARÊNCIA OPERACIONAL</p><h1 className="font-display mt-3 text-2xl font-bold text-white sm:text-3xl">Histórico de manutenções</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Veja as manutenções concluídas e seus períodos programados. Informações internas, pedidos e dados administrativos não são exibidos aqui.</p></header><section className="mt-6 space-y-3">{history.isLoading ? <div className="grid min-h-40 place-items-center rounded-2xl border border-white/10 bg-white/[.025]"><Loader2 className="animate-spin text-emerald-300" /></div> : history.isError ? <div className="rounded-2xl border border-rose-300/20 bg-rose-300/[.06] p-5 text-sm text-rose-100">Não foi possível carregar o histórico agora. <Button type="button" variant="link" onClick={() => history.refetch()} className="h-auto p-0 text-rose-100 underline">Tentar novamente</Button></div> : history.data?.length ? history.data.map((event, index) => <article key={`${event.completedAt}-${index}`} className="flex gap-4 rounded-2xl border border-white/[.08] bg-white/[.025] p-4 sm:p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-emerald-300/20 bg-emerald-300/[.06] text-emerald-200"><CheckCircle2 size={18} /></span><div className="min-w-0"><p className="font-semibold text-white">Manutenção concluída</p><p className="mt-1 text-sm text-slate-400">Modo utilizado: {event.mode === "CATALOG_ONLY" ? "somente catálogo" : "loja temporariamente fechada"}.</p>{event.scheduledStartAt && event.scheduledEndAt ? <p className="mt-3 flex items-center gap-2 text-xs leading-5 text-slate-500"><CalendarClock size={14} /> Programada entre {displayDate(event.scheduledStartAt)} e {displayDate(event.scheduledEndAt)}.</p> : null}<p className="mt-2 text-xs text-slate-500">Concluída em {displayDate(event.completedAt)}</p></div></article>) : <div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-6 text-center text-sm text-slate-400">Nenhuma manutenção concluída foi registrada ainda.</div>}</section></section></main>;
}
