import { StoreHeader } from "@/components/StoreHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowLeft, CheckCircle2, CircleAlert, CreditCard, ExternalLink, Loader2, MessageCircle, PackageCheck, RefreshCw, Server, ShoppingBag, Users } from "lucide-react";
import { Link } from "wouter";

const minecraftLabels = { UNKNOWN: "Aguardando dados", ONLINE: "Online", OFFLINE: "Offline", MAINTENANCE: "Manutenção" } as const;

type Tone = "good" | "attention" | "muted";
function toneClasses(tone: Tone) {
  return tone === "good" ? "border-emerald-300/20 bg-emerald-300/[.08] text-emerald-100" : tone === "attention" ? "border-amber-300/25 bg-amber-300/[.08] text-amber-100" : "border-white/10 bg-white/[.04] text-slate-300";
}
function StatusBadge({ tone, children }: { tone: Tone; children: React.ReactNode }) {
  return <span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[10px] font-bold tracking-[.12em] ${toneClasses(tone)}`}><span className={`h-1.5 w-1.5 rounded-full ${tone === "good" ? "bg-emerald-300" : tone === "attention" ? "bg-amber-300" : "bg-slate-500"}`} />{children}</span>;
}

export default function OperationsStatus() {
  const query = trpc.community.operations.useQuery();
  const data = query.data;
  const minecraft = data?.community?.minecraftStatus ?? "UNKNOWN";
  const deliveryTone: Tone = data?.operations.deliveries.status === "ATTENTION" ? "attention" : "good";
  const minecraftTone: Tone = minecraft === "ONLINE" ? "good" : minecraft === "MAINTENANCE" ? "attention" : "muted";

  return <div className="min-h-screen overflow-x-hidden bg-[#07111d] text-slate-100 selection:bg-emerald-300 selection:text-slate-950">
    <div className="pointer-events-none fixed inset-0 opacity-60 [background-image:linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] [background-size:36px_36px]" />
    <StoreHeader />
    <main className="relative z-10 container pb-20 pt-12 sm:pt-20">
      <Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-300 transition hover:text-emerald-200"><ArrowLeft size={16} /> Voltar à loja</Link>
      <section className="surface-panel relative mt-8 overflow-hidden rounded-[2rem] p-6 sm:p-10">
        <div className="pointer-events-none absolute -right-16 -top-20 h-64 w-64 rounded-full bg-emerald-300/10 blur-3xl" />
        <div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div className="max-w-2xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/[.08] px-3 py-1.5 text-[10px] font-bold tracking-[.15em] text-emerald-100"><Activity size={14} /> CENTRAL OPERACIONAL</div><h1 className="font-display text-4xl font-extrabold tracking-tight text-white sm:text-5xl">Status da PlayStorCraft</h1><p className="mt-4 text-base leading-7 text-slate-300">Acompanhe a comunidade, o servidor Minecraft e a operação de pedidos em um só lugar.</p></div>
          <Button onClick={() => query.refetch()} variant="outline" className="w-full rounded-xl border-white/10 text-slate-200 hover:bg-white/[.06] sm:w-auto"><RefreshCw size={16} className={query.isFetching ? "animate-spin" : ""} /> Atualizar status</Button>
        </div>
      </section>

      {query.isError ? <div className="mt-8 rounded-[1.5rem] border border-rose-300/20 bg-rose-300/[.06] p-7 text-center"><CircleAlert className="mx-auto text-rose-200" /><h2 className="mt-3 font-bold text-white">Não foi possível carregar o status</h2><p className="mt-2 text-sm text-slate-400">Tente novamente em alguns instantes.</p><Button onClick={() => query.refetch()} variant="outline" className="mt-5 border-rose-300/30 text-rose-100">Tentar novamente</Button></div> : <>
        <section className="mt-8 grid gap-5 md:grid-cols-2">
          <article className="surface-panel rounded-[1.6rem] p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-indigo-300/10 text-indigo-100"><MessageCircle size={21} /></div><div><p className="section-kicker text-indigo-200">COMUNIDADE</p><h2 className="font-display mt-1 text-xl font-bold text-white">{data?.community?.discordName ?? "Discord PlayCraftBR"}</h2></div></div><StatusBadge tone={data?.community?.discordOnline ? "good" : "muted"}>{data?.community?.discordOnline ? "CONECTADO" : "AGUARDANDO"}</StatusBadge></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-black/15 p-4"><Users size={16} className="text-indigo-200" /><p className="mt-2 font-mono text-2xl font-bold text-white">{data?.community?.discordMemberCount?.toLocaleString("pt-BR") ?? "—"}</p><p className="text-xs text-slate-500">membros</p></div><div className="rounded-xl border border-white/10 bg-black/15 p-4"><Activity size={16} className="text-emerald-300" /><p className="mt-2 font-mono text-2xl font-bold text-white">{data?.community?.discordOnlineCount?.toLocaleString("pt-BR") ?? "—"}</p><p className="text-xs text-slate-500">online agora</p></div></div>{data?.community?.discordInviteUrl ? <a href={data.community.discordInviteUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-indigo-200 hover:text-indigo-100">Entrar no Discord <ExternalLink size={14} /></a> : null}</article>
          <article className="surface-panel rounded-[1.6rem] p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-300/10 text-emerald-100"><Server size={21} /></div><div><p className="section-kicker text-emerald-200">MINECRAFT PAPER</p><h2 className="font-display mt-1 text-xl font-bold text-white">Servidor PlayStorCraft</h2></div></div><StatusBadge tone={minecraftTone}>{minecraftLabels[minecraft]}</StatusBadge></div><p className="mt-6 min-h-12 text-sm leading-6 text-slate-400">{data?.community?.minecraftMotd ?? "A telemetria do servidor ainda não publicou uma mensagem."}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/[.08] pt-4 text-sm"><span className="text-slate-500">Jogadores online</span><strong className="font-mono text-emerald-200">{typeof data?.community?.minecraftPlayersOnline === "number" ? `${data.community.minecraftPlayersOnline}/${data.community.minecraftPlayersMax ?? "—"}` : "—"}</strong></div><p className="mt-3 text-xs text-slate-500">Versão {data?.community?.minecraftVersion ?? "1.21.x"}</p></article>
        </section>
        <section className="mt-5 grid gap-5 md:grid-cols-2"><article className="surface-panel rounded-[1.6rem] p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-sky-300/10 text-sky-100"><CreditCard size={21} /></div><div><p className="section-kicker text-sky-200">PAGAMENTOS E PEDIDOS</p><h2 className="font-display mt-1 text-xl font-bold text-white">Operação monitorada</h2></div></div><StatusBadge tone="good">INTEGRADO</StatusBadge></div><p className="mt-6 text-sm leading-6 text-slate-400">Os pedidos são acompanhados pelo fluxo seguro da loja e encaminhados para pagamento antes da entrega.</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-black/15 p-4"><ShoppingBag size={16} className="text-sky-200" /><p className="mt-2 font-mono text-2xl font-bold text-white">{data?.operations.payments.pendingOrders ?? "—"}</p><p className="text-xs text-slate-500">em andamento</p></div><div className="rounded-xl border border-white/10 bg-black/15 p-4"><CheckCircle2 size={16} className="text-emerald-300" /><p className="mt-2 font-mono text-2xl font-bold text-white">{data?.operations.payments.settledOrders ?? "—"}</p><p className="text-xs text-slate-500">processados</p></div></div></article><article className="surface-panel rounded-[1.6rem] p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-300/10 text-violet-100"><PackageCheck size={21} /></div><div><p className="section-kicker text-violet-200">ENTREGAS AUTOMÁTICAS</p><h2 className="font-display mt-1 text-xl font-bold text-white">Distribuição no servidor</h2></div></div><StatusBadge tone={deliveryTone}>{data?.operations.deliveries.status === "ATTENTION" ? "ATENÇÃO" : "OPERACIONAL"}</StatusBadge></div><p className="mt-6 text-sm leading-6 text-slate-400">A fila de entregas é acompanhada sem expor dados pessoais ou informações de pedidos publicamente.</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-black/15 p-4"><PackageCheck size={16} className="text-violet-200" /><p className="mt-2 font-mono text-2xl font-bold text-white">{data?.operations.deliveries.pending ?? "—"}</p><p className="text-xs text-slate-500">na fila</p></div><div className="rounded-xl border border-white/10 bg-black/15 p-4"><CircleAlert size={16} className={deliveryTone === "attention" ? "text-amber-200" : "text-slate-500"} /><p className="mt-2 font-mono text-2xl font-bold text-white">{data?.operations.deliveries.failed ?? "—"}</p><p className="text-xs text-slate-500">com atenção</p></div></div></article></section>
        <p className="mt-6 text-center text-xs text-slate-500">Atualização consultada {data?.operations.refreshedAt ? new Date(data.operations.refreshedAt).toLocaleString("pt-BR") : "—"}. Os indicadores representam a última leitura disponível.</p>
      </>}
    </main>
  </div>;
}
