import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { StoreHeader } from "@/components/StoreHeader";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Loader2, PackageCheck, ShoppingBag } from "lucide-react";
import { Link } from "wouter";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const statusStyle: Record<string, string> = { PENDING: "bg-amber-300/10 text-amber-200", WAITING_PAYMENT: "bg-amber-300/10 text-amber-200", PAID: "bg-sky-300/10 text-sky-200", PROCESSING: "bg-sky-300/10 text-sky-200", COMPLETED: "bg-emerald-300/10 text-emerald-200", CANCELLED: "bg-slate-300/10 text-slate-300", REFUNDED: "bg-violet-300/10 text-violet-200", FAILED: "bg-rose-300/10 text-rose-200" };

export default function OrderHistory() {
  const { isAuthenticated, loading } = useAuth();
  const orders = trpc.orders.mine.useQuery(undefined, { enabled: isAuthenticated });
  if (!loading && !isAuthenticated) return <main className="account-page grid min-h-screen place-items-center p-6 text-center text-white"><div className="account-guard"><div className="status-orb mx-auto"><ShoppingBag size={21} /></div><p className="section-kicker mt-5">ÁREA DO JOGADOR</p><h1 className="font-display mt-2 text-2xl font-bold">Suas recompensas estão protegidas</h1><p className="mt-3 text-sm leading-6 text-slate-400">Entre para consultar pedidos, descontos aplicados e o andamento da entrega no servidor.</p><Button onClick={startLogin} className="mt-6 bg-emerald-300 text-slate-950 hover:bg-emerald-200">Entrar na minha conta</Button></div></main>;
  return <div className="account-page text-slate-100"><StoreHeader /><main className="p-5 sm:p-10"><div className="mx-auto max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 transition hover:text-emerald-200"><ArrowLeft size={16} /> Voltar aos benefícios</Link><div className="mt-8 flex items-end justify-between gap-5"><div><p className="section-kicker">ÁREA DO JOGADOR</p><h1 className="font-display mt-2 text-4xl font-bold text-white">Minhas recompensas</h1><p className="mt-2 text-sm text-slate-400">Acompanhe pagamentos e entregas em um único lugar.</p></div><div className="status-orb hidden sm:grid"><PackageCheck size={21} /></div></div>{orders.isLoading ? <div className="grid h-64 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div> : orders.isError ? <div className="surface-panel mt-8 rounded-[1.5rem] p-12 text-center"><h2 className="font-display text-xl font-bold text-white">Não foi possível carregar seus pedidos</h2><p className="mt-2 text-sm text-slate-400">Tente novamente em alguns instantes.</p><Button onClick={() => orders.refetch()} className="mt-5 bg-emerald-300 text-slate-950 hover:bg-emerald-200">Tentar novamente</Button></div> : orders.data?.length ? <div className="surface-panel mt-8 overflow-hidden rounded-[1.5rem]"><div className="hidden grid-cols-[1.4fr_.8fr_.8fr] gap-5 border-b border-white/10 bg-white/[.03] px-5 py-3 text-[10px] font-bold tracking-[.14em] text-slate-500 sm:grid"><span>PEDIDO</span><span>STATUS</span><span className="text-right">TOTAL</span></div>{orders.data.map(order => <div key={order.id} className="grid gap-3 border-b border-white/[.07] px-5 py-5 last:border-none transition hover:bg-white/[.025] sm:grid-cols-[1.4fr_.8fr_.8fr] sm:items-center"><div><Link href={`/orders/${order.id}`} className="font-mono text-sm font-bold text-white hover:text-emerald-200">{order.orderNumber}</Link><p className="mt-1 text-xs text-slate-500">{new Date(order.createdAt).toLocaleString("pt-BR")}</p></div><div><Badge className={`border ${statusStyle[order.status] ?? "border-white/10 bg-white/10 text-slate-300"}`}>{order.status.replaceAll("_", " ")}</Badge></div><p className="font-mono text-right text-sm font-bold text-emerald-200">{money.format(order.totalCents / 100)}</p></div>)}</div> : <div className="empty-state mt-8 rounded-[1.5rem] p-12 text-center"><div className="status-orb mx-auto"><ShoppingBag size={21} /></div><p className="mt-4 text-slate-300">Você ainda não equipou nenhum benefício.</p><Link href="/" className="mt-5 inline-flex text-sm font-bold text-emerald-300 hover:text-emerald-200">Explorar a loja</Link></div>}</div></main></div>;
}
