import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Loader2, PackageCheck } from "lucide-react";
import { Link, useRoute } from "wouter";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function OrderDetail() {
  const { isAuthenticated, loading } = useAuth();
  const [, params] = useRoute("/orders/:id");
  const order = trpc.orders.byId.useQuery({ id: params?.id ?? "00000000-0000-0000-0000-000000000000" }, { enabled: isAuthenticated && Boolean(params?.id) });
  if (loading || order.isLoading) return <main className="grid min-h-screen place-items-center bg-[#07111d]"><Loader2 className="animate-spin text-emerald-300" /></main>;
  if (order.isError) return <main className="grid min-h-screen place-items-center bg-[#07111d] p-6 text-center text-white"><div><h1 className="text-2xl font-bold">Não foi possível carregar este pedido</h1><p className="mt-2 text-sm text-slate-400">Tente novamente em alguns instantes.</p><Button onClick={() => order.refetch()} className="mt-5 bg-emerald-300 text-slate-950 hover:bg-emerald-200">Tentar novamente</Button></div></main>;
  if (!isAuthenticated || !order.data) return <main className="grid min-h-screen place-items-center bg-[#07111d] p-6 text-center text-white"><div><h1 className="text-2xl font-bold">Pedido não localizado</h1><Link href="/orders" className="mt-4 inline-flex text-sm font-bold text-emerald-300">Voltar aos pedidos</Link></div></main>;
  const detail = order.data;
  return <main className="min-h-screen bg-[#07111d] px-5 py-8 text-slate-100 sm:p-12"><div className="mx-auto max-w-3xl"><Link href="/orders" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-emerald-200"><ArrowLeft size={16} /> Meus pedidos</Link><div className="mt-8 overflow-hidden rounded-[1.6rem] border border-white/10 bg-slate-950/35"><div className="border-b border-white/10 p-6 sm:p-8"><p className="font-mono text-xs font-bold tracking-[.16em] text-emerald-300">PEDIDO {detail.orderNumber}</p><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-white">Acompanhamento do pedido</h1><p className="mt-2 text-sm text-slate-400">Criado em {new Date(detail.createdAt).toLocaleString("pt-BR")}</p></div><span className="rounded-xl bg-emerald-300/10 px-4 py-2 font-mono text-xs font-bold text-emerald-200">{detail.status.replaceAll("_", " ")}</span></div></div><div className="space-y-3 p-6 sm:p-8">{detail.items.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.03] p-4"><div><p className="font-semibold text-white">{item.productName}</p><p className="mt-1 text-xs text-slate-400">{item.durationDays ? `${item.durationDays} dias` : "Permanente"}</p></div><p className="font-mono text-sm font-bold text-emerald-200">{money.format(item.unitPriceCents / 100)}</p></div>)}</div><div className="flex items-center justify-between border-t border-white/10 bg-white/[.025] p-6 sm:px-8"><span className="text-sm text-slate-400">Total</span><strong className="font-mono text-2xl text-white">{money.format(detail.totalCents / 100)}</strong></div></div><div className="mt-5 flex gap-3 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.06] p-4 text-sm text-emerald-50"><PackageCheck className="shrink-0 text-emerald-300" size={20} /><p>Após a confirmação do pagamento pelo gateway, o pedido avançará para processamento e a entrega será disponibilizada ao servidor configurado.</p></div></div></main>;
}
