import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Loader2, PackageCheck, ShoppingBag } from "lucide-react";
import { Link } from "wouter";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const statusStyle: Record<string, string> = { PENDING: "bg-amber-300/10 text-amber-200", WAITING_PAYMENT: "bg-amber-300/10 text-amber-200", PAID: "bg-sky-300/10 text-sky-200", PROCESSING: "bg-sky-300/10 text-sky-200", COMPLETED: "bg-emerald-300/10 text-emerald-200", CANCELLED: "bg-slate-300/10 text-slate-300", REFUNDED: "bg-violet-300/10 text-violet-200", FAILED: "bg-rose-300/10 text-rose-200" };

export default function OrderHistory() {
  const { isAuthenticated, loading } = useAuth();
  const orders = trpc.orders.mine.useQuery(undefined, { enabled: isAuthenticated });
  if (!loading && !isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#07111d] p-6 text-center text-white"><div><ShoppingBag className="mx-auto mb-4 text-emerald-300" /><h1 className="text-2xl font-bold">Entre para ver seus pedidos</h1><p className="mt-2 text-sm text-slate-400">Seu histórico de compras fica protegido pela sua conta.</p><Button onClick={startLogin} className="mt-6 bg-emerald-300 text-slate-950 hover:bg-emerald-200">Entrar</Button></div></main>;
  return <main className="min-h-screen bg-[#07111d] p-5 text-slate-100 sm:p-10"><div className="mx-auto max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-400 transition hover:text-emerald-200"><ArrowLeft size={16} /> Voltar para a loja</Link><div className="mt-8 flex items-end justify-between gap-5"><div><p className="font-mono text-xs font-bold tracking-[.16em] text-emerald-300">ÁREA DO JOGADOR</p><h1 className="mt-2 text-4xl font-black tracking-tight text-white">Meus pedidos</h1></div><PackageCheck className="text-emerald-300" size={34} /></div>{orders.isLoading ? <div className="grid h-64 place-items-center"><Loader2 className="animate-spin text-emerald-300" /></div> : orders.isError ? <div className="mt-8 rounded-[1.5rem] border border-rose-300/20 bg-rose-300/[.06] p-12 text-center"><h2 className="text-xl font-bold text-white">Não foi possível carregar seus pedidos</h2><p className="mt-2 text-sm text-slate-400">Tente novamente em alguns instantes.</p><Button onClick={() => orders.refetch()} className="mt-5 bg-emerald-300 text-slate-950 hover:bg-emerald-200">Tentar novamente</Button></div> : orders.data?.length ? <div className="mt-8 overflow-hidden rounded-[1.5rem] border border-white/10"><div className="hidden grid-cols-[1.4fr_.8fr_.8fr] gap-5 border-b border-white/10 bg-white/[.035] px-5 py-3 text-xs font-bold tracking-[.1em] text-slate-500 sm:grid"><span>PEDIDO</span><span>STATUS</span><span className="text-right">TOTAL</span></div>{orders.data.map(order => <div key={order.id} className="grid gap-3 border-b border-white/10 bg-slate-950/30 px-5 py-5 last:border-none sm:grid-cols-[1.4fr_.8fr_.8fr] sm:items-center"><div><Link href={`/orders/${order.id}`} className="font-mono text-sm font-bold text-white hover:text-emerald-200">{order.orderNumber}</Link><p className="mt-1 text-xs text-slate-500">{new Date(order.createdAt).toLocaleString("pt-BR")}</p></div><div><Badge className={`border-0 ${statusStyle[order.status] ?? "bg-white/10 text-slate-300"}`}>{order.status.replaceAll("_", " ")}</Badge></div><p className="font-mono text-right text-sm font-bold text-emerald-200">{money.format(order.totalCents / 100)}</p></div>)}</div> : <div className="mt-8 rounded-[1.5rem] border border-dashed border-white/15 bg-white/[.025] p-12 text-center"><ShoppingBag className="mx-auto text-slate-600" /><p className="mt-4 text-slate-400">Você ainda não fez nenhum pedido.</p><Link href="/" className="mt-5 inline-flex text-sm font-bold text-emerald-300 hover:text-emerald-200">Explorar a loja</Link></div>}</div></main>;
}
